#!/usr/bin/env python3
"""Agent PR ledger (definition v1.0).

What is counted is whether a review is present as an *auditable record*,
not whether anyone looked. If the diff was reviewed inside the agent's own
interface and then merged, that review left no record on GitHub.

Definition v1.0 counts a review record only from someone **other than the PR
author**. A comment the author leaves on their own PR — an instruction to the
agent, a note to themselves — is not third-party review.
"""
from __future__ import annotations
import json, os, re, sys, time, urllib.request, urllib.error, urllib.parse
from collections import Counter
from datetime import datetime

DEFINITION_VERSION = "1.0"
API = "https://api.github.com"

BOT_AUTHORS = {
    "copilot": "Copilot",
    "copilot-swe-agent[bot]": "Copilot",
    "devin-ai-integration[bot]": "Devin",
    "devin[bot]": "Devin",
}
BRANCH_PATTERNS = [
    (re.compile(r"^codex/", re.I), "OpenAI_Codex"),
    (re.compile(r"^cursor/", re.I), "Cursor"),
    (re.compile(r"^claude/", re.I), "Claude_Code"),
    (re.compile(r"^jules/", re.I), "Jules"),
    (re.compile(r"^devin/", re.I), "Devin"),
]
BODY_PATTERNS = [
    (re.compile(r"generated with \[?claude code", re.I), "Claude_Code"),
    (re.compile(r"co-authored-by:\s*claude", re.I), "Claude_Code"),
    (re.compile(r"\bopenai codex\b|generated by codex", re.I), "OpenAI_Codex"),
    (re.compile(r"generated with cursor|co-authored-by:\s*cursor", re.I), "Cursor"),
]
WEAK_HINTS = [
    re.compile(r"\b(ai[- ]generated|generated by (an )?ai|autonomous agent)\b", re.I),
    re.compile(r"co-authored-by:.*\b(bot|ai|agent)\b", re.I),
]
WEAK_BRANCH = re.compile(r"^(ai|bot|agent)[-/]", re.I)
IDENTITY_TYPE = {"Copilot": "bot", "Devin": "bot", "Jules": "bot",
                 "OpenAI_Codex": "self", "Cursor": "self", "Claude_Code": "self"}


def classify(pr: dict) -> tuple[str | None, str]:
    """Return (agent, basis). Basis is author|branch|body|trace|none."""
    login = ((pr.get("user") or {}).get("login") or "").lower()
    if login in BOT_AUTHORS:
        return BOT_AUTHORS[login], "author"
    ref = (pr.get("head") or {}).get("ref") or ""
    for pat, name in BRANCH_PATTERNS:
        if pat.search(ref):
            return name, "branch"
    body = pr.get("body") or ""
    for pat, name in BODY_PATTERNS:
        if pat.search(body):
            return name, "body"
    if WEAK_BRANCH.search(ref) or any(p.search(body) for p in WEAK_HINTS):
        return None, "trace"
    return None, "none"


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """Authorization ヘッダが別ホストへ転送されないよう、リダイレクトを追わない。"""
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        if urllib.parse.urlparse(newurl).netloc != "api.github.com":
            return None
        return super().redirect_request(req, fp, code, msg, headers, newurl)


class GitHub:
    def __init__(self, token: str | None = None):
        self.token = token or os.environ.get("GITHUB_TOKEN")
        self.calls = 0
        self._op = None

    def _opener(self):
        if self._op is None:
            self._op = urllib.request.build_opener(_NoRedirect())
        return self._op.open

    def get(self, path: str, params: dict | None = None):
        url = API + path + ("?" + "&".join(f"{k}={v}" for k, v in params.items()) if params else "")
        req = urllib.request.Request(url, headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "agent-pr-ledger",
            **({"Authorization": f"Bearer {self.token}"} if self.token else {}),
        })
        for attempt in range(3):
            try:
                with urllib.request.urlopen(self._opener(), req, timeout=30) as r:
                    if urllib.parse.urlparse(r.geturl()).netloc != "api.github.com":
                        raise RuntimeError("refusing redirect off api.github.com")
                    self.calls += 1
                    return json.loads(r.read().decode())
            except urllib.error.HTTPError as e:
                remaining = e.headers.get("X-RateLimit-Remaining")
                if e.code == 403 and remaining not in (None, "0"):
                    raise                      # レート制限ではなく認可の問題
                if e.code in (403, 429) and attempt < 2:
                    wait = e.headers.get("Retry-After")
                    time.sleep(float(wait) if wait else 2 ** attempt)
                    continue
                raise

    def paged(self, path: str, extra: dict | None = None, cap: int = 1000):
        out, page = [], 1
        while len(out) < cap:
            batch = self.get(path, {"per_page": 100, "page": page, **(extra or {})})
            if not batch:
                break
            out.extend(batch)
            if len(batch) < 100:
                break
            page += 1
        return out[:cap]

    def pulls(self, repo, limit=100):
        return self.paged(f"/repos/{repo}/pulls",
                          {"state": "all", "sort": "created", "direction": "desc"}, limit)

    def reviews(self, repo, num):
        return self.paged(f"/repos/{repo}/pulls/{num}/reviews")

    def comments(self, repo, num):
        return self.paged(f"/repos/{repo}/issues/{num}/comments")

    def review_comments(self, repo, num):
        return self.paged(f"/repos/{repo}/pulls/{num}/comments")


def ts(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00")) if s else None


def third_party(entry: dict, author: str) -> bool:
    """Not a bot, and not the PR author."""
    u = entry.get("user") or {}
    return u.get("type") != "Bot" and (u.get("login") or "") != author


def classify_merge(pr, reviews, comments, review_comments) -> str:
    merged = ts(pr.get("merged_at"))
    if not merged:
        return "not_merged"
    author = ((pr.get("user") or {}).get("login")) or ""
    stamps = [ts(r.get("submitted_at")) for r in reviews if third_party(r, author)]
    for src in (comments, review_comments):
        stamps += [ts(c.get("created_at")) for c in src if third_party(c, author)]
    return "recorded" if any(s and s < merged for s in stamps) else "unrecorded"


def build(repo: str, limit: int = 100, token: str | None = None) -> dict:
    gh = GitHub(token)
    rows, coverage, all_dates = [], Counter(), []
    for pr in gh.pulls(repo, limit):
        all_dates.append(pr["created_at"])
        agent, how = classify(pr)
        coverage[how] += 1
        if not agent:
            continue
        n = pr["number"]
        rows.append({
            "number": n, "agent": agent, "identity_type": IDENTITY_TYPE.get(agent, "unknown"),
            "detected_by": how, "created_at": pr["created_at"], "merged_at": pr.get("merged_at"),
            "outcome": classify_merge(pr, gh.reviews(repo, n), gh.comments(repo, n),
                                      gh.review_comments(repo, n)),
        })
    d = sorted(all_dates)
    # 8: detection は常に全キーを 0 で埋める
    cov = {k: coverage.get(k, 0) for k in ("author", "branch", "body", "trace", "none")}
    return {"repo": repo, "definition_version": DEFINITION_VERSION,
            "rows": rows, "coverage": cov, "api_calls": gh.calls,
            "scanned_prs": len(all_dates), "limit": limit,
            "span": [d[0][:10], d[-1][:10]] if d else None}


TEXT = {
    "en": dict(
        title="Agent PR ledger", period="all time", none="No agent-authored pull requests found.",
        total="Agent PRs in this repository", rec="merged with a review record",
        unrec="merged without a review record", nm="not merged",
        warn="{p}% of merged agent PRs have no review record.",
        allrec="All {n} merged agent PRs have a review record.",
        note1="This is a count, not a judgement — definition v{v}",
        note2="Comparison with other repositories is not shown in v0.",
        caveat=['"No review record" does not mean nobody looked. If the diff was reviewed',
                "inside the agent's own interface, that review leaves no record on GitHub.",
                "This counts whether a review record exists — not whether a review happened."],
        cls="Classified as", types={"bot": "posted under a bot account (external contribution)",
                                    "self": "posted under your own account (your own work)",
                                    "unknown": "mixed"},
        breakdown="By agent (conventions differ — do not compare across)",
        det="Detection: {a} certain (author) / {b} inferred (branch) / {c} inferred (body)",
        trace="{n} PR(s) show an agent trace we could not attribute — excluded from the ledger.",
        human="({n} PR(s) with no agent trace are treated as human PRs and are out of scope.)",
        norec="no record", nonemerged="(none merged)",
        window="scanned: the {k} most recent PRs ({a} to {b})",
        window_month="month: {m}", trend="Recent months",
        ofthese="(percentages below are of these)", of_merged="(rates are of merged PRs)",
        det_all="Detection across all scanned PRs: {a} certain (author) / {b} inferred (branch) / {c} inferred (body)",
    ),
    "ja": dict(
        title="エージェントPRの台帳", period="全期間", none="エージェントのPRは見つかりませんでした。",
        total="このリポジトリに来たエージェントのPR", rec="審査の記録があってからマージ",
        unrec="審査の記録がないままマージ", nm="マージされず",
        warn="マージされたPRのうち、審査の記録がないものが {p}% あります。",
        allrec="マージされた{n}件は、すべて審査の記録があります。",
        note1="数え方の記述です。良し悪しの判定はしません → 定義 v{v}",
        note2="他のリポジトリとの比較は v0 では出しません。",
        caveat=["「記録がない」は「誰も見ていない」ではありません。エージェントの画面の中で",
                "確認してからマージした場合、その審査はGitHub上に記録として残りません。",
                "数えているのは「審査の記録が残っているか」であって、審査が行われたかではありません。"],
        cls="分類", types={"bot": "ボット名義型（外部寄稿）", "self": "本人名義型（自作業）", "unknown": "混成"},
        breakdown="内訳（作法が違うので、横に比べないでください）",
        det="判定の内訳：作成者名義で確定 {a}件 ／ ブランチ名から推定 {b}件 ／ 本文から推定 {c}件",
        trace="痕跡はあるがエージェントを確定できなかったPRが {n}件あります（台帳には含めていません）",
        human="（エージェントの痕跡が無い {n}件は、人間のPRとして台帳の対象外です）",
        norec="記録なし", nonemerged="（マージなし）",
        window="走査対象：直近{k}件のPR（{a}〜{b}）", window_month="対象月：{m}", trend="直近の推移",
        ofthese="（以下の%はこの件数に対する割合）", of_merged="（%はマージ済みに対する割合）",
        det_all="判定の内訳（走査した全PR）：作成者名義で確定 {a}件 ／ ブランチ名から推定 {b}件 ／ 本文から推定 {c}件",
    ),
}


def monthly(led: dict) -> list[tuple[str, int, int, int]]:
    """(月, 件数, 記録あり, 記録なし) を古い順に返す。"""
    out = {}
    for r in led["rows"]:
        k = r["created_at"][:7]
        a, b, c = out.get(k, (0, 0, 0))
        out[k] = (a + 1, b + (r["outcome"] == "recorded"), c + (r["outcome"] == "unrecorded"))
    return [(k, *v) for k, v in sorted(out.items())]


def render(led: dict, month: str | None = None, lang: str = "en") -> str:
    T = TEXT.get(lang, TEXT["en"])
    rows = [r for r in led["rows"] if not month or r["created_at"][:7] == month]
    if not rows:
        return T["none"]
    c = Counter(r["outcome"] for r in rows)
    rec, unrec, nm, n = c["recorded"], c["unrecorded"], c["not_merged"], len(rows)
    merged = rec + unrec
    pc = lambda x: f"{x/n*100:.0f}%"
    types = Counter(r["identity_type"] for r in rows)
    tkey = types.most_common(1)[0][0] if len(types) == 1 else "unknown"
    span = led.get("span")
    win = (T["window"].format(k=led.get("scanned_prs", "?"),
                              a=span[0] if span else "?", b=span[1] if span else "?")
           if not month else T["window_month"].format(m=month))
    L = [f"📒 {T['title']}", f"  {win}", "",
         f"  {T['total']}  {n}   {T['ofthese']}",
         f"    ├ {T['rec']}  {rec} ({pc(rec)})",
         f"    ├ {T['unrec']}  {unrec} ({pc(unrec)})",
         f"    └ {T['nm']}  {nm} ({pc(nm)})", ""]
    if merged and unrec:
        L += [f"  {T['warn'].format(p=f'{unrec/merged*100:.0f}')}", ""]
    elif merged:
        L += [f"  {T['allrec'].format(n=merged)}", ""]
    L += [f"  ({T['note1'].format(v=led['definition_version'])})", f"  {T['note2']}", ""]
    L += ["  " + x for x in T["caveat"]] + [""]
    L += [f"  {T['cls']}: {T['types'][tkey]}", f"  {T['breakdown']}"]
    for a, k in Counter(r["agent"] for r in rows).most_common():
        sm = [r for r in rows if r["agent"] == a and r["outcome"] != "not_merged"]
        u = sum(1 for r in sm if r["outcome"] == "unrecorded")
        L.append(f"    {a:<14} {k:>3}  {T['norec']} {u/len(sm)*100:.0f}%" if sm
                 else f"    {a:<14} {k:>3}  {T['nonemerged']}")
    mt = monthly(led)
    if len(mt) > 1 and not month:
        L += ["", f"  {T['trend']}  {T['of_merged']}"]
        for k, tot, rc, ur in mt[-6:]:
            m2 = rc + ur
            L.append(f"    {k}  {tot:>3} PRs" + (f"  ({m2} merged)  {T['norec']} {ur/m2*100:.0f}%" if m2
                                                 else f"  {T['nonemerged']}"))
    cov = led["coverage"]
    L += ["", "  " + (T["det_all"] if month else T["det"]).format(
        a=cov.get("author", 0), b=cov.get("branch", 0), c=cov.get("body", 0))]
    if cov.get("trace"):
        L.append(f"  ⚠ {T['trace'].format(n=cov['trace'])}")
    L.append(f"  {T['human'].format(n=cov.get('none', 0))}")
    return "\n".join(L)


def main(argv):
    if len(argv) < 2:
        print("usage: ledger.py OWNER/REPO [limit] [--lang en|ja] [--month YYYY-MM]", file=sys.stderr)
        return 2
    limit = 100
    if len(argv) > 2 and not argv[2].startswith("--"):
        if not argv[2].isdigit() or int(argv[2]) < 1:
            print(f"error: limit must be a positive integer, got {argv[2]!r}", file=sys.stderr)
            return 2
        limit = int(argv[2])
    lang = argv[argv.index("--lang") + 1] if "--lang" in argv else "en"
    month = argv[argv.index("--month") + 1] if "--month" in argv else None
    led = build(argv[1], limit)
    if "--json" in argv:
        rows = [r for r in led["rows"] if not month or r["created_at"][:7] == month]
        led = {**led, "rows": rows, "month": month}
        c = Counter(r["outcome"] for r in rows)
        print(json.dumps({
            "schema": "agent-pr-ledger/v1",
            "definition_version": led["definition_version"],
            "repo": led["repo"], "scanned_prs": led["scanned_prs"], "span": led["span"],
            "month": month,
            "counts": {"agent_prs": len(rows), "merged_with_review_record": c["recorded"],
                       "merged_without_review_record": c["unrecorded"], "not_merged": c["not_merged"]},
            "detection": led["coverage"],
            "detection_scope": "all scanned PRs (not filtered by --month)",
            "monthly": [{"month": k, "agent_prs": t, "with_record": r, "without_record": u}
                        for k, t, r, u in monthly(led)],
            "prs": led["rows"],
        }, indent=2))
        return 0
    print(render(led, month, lang))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
